print "esta es una prueba de print"
puts "esta es una prueba de puts"
print "esta es una prueba de print"
puts "esta es una prueba de puts"
print "esta es una prueba de print"
puts "esta es una prueba de puts"
print "esta es una prueba de print"
